# Generated by Django 4.2.7 on 2025-11-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_payment_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frontend_image',
            field=models.CharField(blank=True, help_text="Filename of optimized image in frontend (e.g., 'geometric_planter.jpg'). Leave blank to use uploaded image.", max_length=200),
        ),
    ]
