# Generated by Django 4.2.7 on 2026-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_image_url_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Primary image — paste the full S3 URL here', max_length=500),
        ),
    ]
